import { NgModule } from '@angular/core';
import {
  MatButtonModule,
  MatCardModule,
  MatCheckboxModule,
  MatChipsModule,
  MatFormFieldModule,
  MatIconModule,
  MatInputModule,
  MatListModule,
  MatPaginatorModule,
  MatRadioModule,
  MatSidenavModule,
  MatSnackBarModule,
  MatTabsModule,
  MatToolbarModule,
  MatBottomSheetModule,
  MatSlideToggleModule,
  MatProgressBarModule,
  MatSelectModule,
  MatTableModule,
  MatDialogModule,
} from '@angular/material';

@NgModule({
  imports: [],
  exports: [
    MatButtonModule,
    MatCardModule,
    MatCheckboxModule,
    MatChipsModule,
    MatFormFieldModule,
    MatIconModule,
    MatInputModule,
    MatListModule,
    MatPaginatorModule,
    MatRadioModule,
    MatSidenavModule,
    MatSnackBarModule,
    MatTabsModule,
    MatToolbarModule,
    MatBottomSheetModule,
    MatSlideToggleModule,
    MatProgressBarModule,
    MatSelectModule,
    MatTableModule,
    MatDialogModule,
  ],
  declarations: [],
})
export class MaterialModule {
}
